README.md
Week2-IntroTojavaScript/2.3-JSOperators&FlowControl/2.3-Activities/5-Stu-MoreIfElseStatements.js
Week8-RestApiBackend/8.1-HTTP-Rest-API/8.1-HTTP-Web-server.md
Week8-RestApiBackend/8.3-Document-Store-API-MongoDB/8.3-Document-Store-API-MongoDB.md
Week9-MoreRestApiBackend/9.1-Abstraction-Relationships/9.1-Abstraction-Relationships.md
Week9-MoreRestApiBackend/9.2-Connecting-Frontend-to-Backend/9.2-Connecting-Frontend-to-Backend.md
Week9-MoreRestApiBackend/9.3-Hosting-On-Heroku/9.3-Hosting-On-Heroku.md
Week9-MoreRestApiBackend/Week9-Homework/9-Homework.md

Corrected spelling errors in week 8 updated week 9, and updated the Readme file

Week 9 and other small updates

---

.vscode/settings.json
Section03-JavaScript/3.2-DataCollections.md
Section05-HTMLAndCSS2/5.2-JavaScriptClasses.md

Hi Folks, 
Happy weekend to you !
During whiteboarding we identified a gap in the curriculum in that the student were not sufficiently exposed to helpful string and array methods.
I have added a few String Methods to Section 3 and a few Array Methods to Section 5.
Kindly please review these and let me know what your thoughts are.
Thanks!
Johan

Adding Additional methods to the April curriculum 

---

Section06-SinglePageApplication/6.2-SPAComponents.md

Hi there Folks,
I have added a section #16 as we discussed, to explain how to incorporate images inside of the template literals.
Please review this and let me know if I missed anything.
Also let me know if there is something else we should add.
Thanks!
Johan

Add "using images in template literals" - section 16

---

Section02/2.1-EssentialDevTools.md
Section02/2.2-JSdataTypeAndVariables.md
Section02/2.3-JSOperatorsAndFlowControl.md
Section03/3.1-Functions.md
Section03/3.2-DataCollections.md
Section03/3.3-HTMLAndCSSBasics.md
Section04/4.1-DocumentObjectModel.md
Section04/4.2-ArrayMethods1.md
Section04/4.3-ArrayMethods2.md
Section05/5.2-JavaScriptClasses.md

I've gotten started on this ticket. Let me know what you think

Explanations of why we introduce topics

---

AddendumOfResources/AddendumOfResources.md
Section05/5.1-IntermediateHTMLAndCSS.md
Section05/5.2-JavaScriptClasses.md
Section05/5.3-CapstoneWork.md
Section05/Activities/5.1-Activities/ABetterForm.html
Section05/Activities/5.1-Activities/index.html
Section05/Activities/5.1-Activities/style.css
Section05/Activities/5.2-Activities/5.2.1-FunctionConstructors.md
Section05/Activities/5.2-Activities/5.2.2-MoreFunctionConstructors.md
Section05/Activities/5.3-Activities/index.html
Section05/Activities/5.3-Activities/style.css

OK, so here are the updates for section 5.
There might be a few additional little fixes here and there as well...
Kindly please check and let me know.

Section5updates

---

Section06/6.3-SPAState.md

Line 221 - was }}). - is now }}).resolve():
Line 288 - was Resources/CreatingAnSPA - is now Resources/CreatingAnSPA.md

6.3 Quick Typo Fixes

---

Section00/0-PreHomework.md

Hi Folks, 
Here is the PR for story ticket #225  
This story is to add the Agile materials to the course pre-work
Please review and let me know if something else needs to be added.
Thanks,
Johan

Add materials on agile to section 0

---

Section00/0-PreHomework.md
Section02/Activities/2.2-Activities/2.2.1-JSVariablesAndPrimatives.md
Section02/Activities/2.2-Activities/2.2.2-JSVariablesAndPrimitives.md
Section02/Activities/2.2-Activities/2.2.3-JSMorePrimitives.md
Section02/Activities/2.2-Activities/2.2.4-JSMorePrimitives.md
Section02/Activities/2.3-Activities/2.3.1-MathOperators.md
Section02/Activities/2.3-Activities/2.3.2-DataCoersionIntro.md
Section02/Activities/2.3-Activities/2.3.3-ComparisonOperators.md
Section02/Activities/2.3-Activities/2.3.4-IfElseStatements.md
Section02/Activities/2.3-Activities/2.3.5-MoreIfElseStatements.md
Section02/Activities/2.3-Activities/2.3.6-TruthyFalsyAndLogicalOperators.md
Section02/Activities/2.3-Activities/2.3.7-WhileLoops.md
Section02/Activities/2.3-Activities/2.3.8-ForLoops.md

Hello Folks,
This is the PR for the branch in which I have updated the Section 2 Activities
Kindly please review and give me your feedback on any corrections you would like me to make.
Thanks!

Update Section 2 Activities Scc-234

---

Section03/Activities/3.1-Activities/3.1.1-FunctionDeclaration.md
Section03/Activities/3.1-Activities/3.1.2-FunctionInvovation.md
Section03/Activities/3.1-Activities/3.1.3-ReturnsAndShortCircuiting.md
Section03/Activities/3.1-Activities/3.1.4-Parameters.md
Section03/Activities/3.1-Activities/3.1.5-FunctionsAndScope.md
Section03/Activities/3.1-Activities/3.1.6-Callbacks.md
Section03/Activities/3.1-Activities/3.1.7-ArrowSyntax.md
Section03/Activities/3.2-Activities/3.2.1-Arrays.md
Section03/Activities/3.2-Activities/3.2.2-MorePracticeWithObjects.md
Section03/Activities/3.2-Activities/3.2.3-Mutation.md
Section03/Activities/3.2-Activities/3.2.4-ReferenceAndValue.md

Hi Folks,
Here is the PR on the branch to Replace the use of Node.js in ALL activities with Replit or the Chrome Browser console
Kindly please review and let me know if there are any changes that I should add.
Thanks

Scc-239 Replace the use of Node.js in ALL activities with browser

---

Section05/5-Homework.md

SCC-246 Fix URL in Section 5 homework

---

Section05/5-Homework.md

Because there was so much material, I did *not* remove the divider lines as suggested, but did reorganize the flow as described in ticket and instead added a "1 of 4", "2 of  o4" strategy and added a large warning at the beginning of the homework section that homework would consist of 4 separate sections. Can alter before merge if it doesn't appear to flow as logically to reviewers as it did to me at the time.

Reorganize section 5 homework to flow more logically

---

AddendumOfResources/Glossary/Glossary.md

Not to be confused with SCC-209, this shows the completion of the Glossary as well as some updates to reflect changes in development

scc-209 Completion of Glossary

---

Section03/3.3-HTMLAndCSSBasics.md

Corrected pull request to merge to development; had failed to deselect default Master branch prior.
- Corrected minor typo on the fly

Correct minor typo on the fly

---

Section10/10.3-Unit-Testing.md

Hi Folks,
Kindly please review this PR so that we can get the latest changes to the Jasmin curriculum into Development, as well as into the the Main branch before week 10
Thanking you sincerely

update jasmine curriculum 

---

Section05/5-Homework.md

Made correction to dev be the same on master

Master fixes to Section 5 Homework

---

Section06/6.3-SPAState.md

Hello Folks,
I updates section 6.3 according to the notes in ticket #296
Kindly please review these changes and comment as needed.
Thanks!

updated sec 6.3

---

Section02/Activities/2.3-Activities/2.3.2-ComparisonOperatorsAndIfElseStatements.md
Section02/Activities/2.3-Activities/2.3.3-SwitchStatements.md
Section02/Activities/2.3-Activities/2.3.4-TruthyFalsyAndLogicalOperators.md

Found some typos in 2.3 Activities in Curriculum while making updates to the Teachers Guide

Fixed Various Typos in 2.3 Activities

---

Section10/10.3-Unit-Testing.md

Fixed some typos, restructured Activities 2 and 3 a little bit for a better flow.

Fixed typos, restructured Activities a tiny bit

---

Section04/4.2-ArrayMethods1.md

Hi Folks,
I've changed up section 4.2 as detailed in the ticket.
I delete these sting methods from section 4.2
.startswith() / endswith()
.charAt()
.repeat()
I added the following Array Methods into the array section
.revers()
.includes()
Because the 2 array methods are so simple, I did not add any new activities for these to methods.
Kindly please review this {R and let me know what changes need to be made.

Rework section 4.2

---

Section07/7.2-APIsAndAxios1.md

Removed the duplicate section on securing variables with dotenv
Rearranged Sections for easier flow
Before: Axios Library > API Authorization > Open Weather Map (contained saving to state and router.hook example) > Secure with dotenv > Pizza
After:  Axios Library > API Authorization > Open Weather Map (no longer saves to state, no router.hook example) > Securing with dotenv > New Section on Storing Data in State (contains router.hooks example) > Pizza
Added clarity to sections where things might be confusing

Updated 7.2
